type Query {
    image(id: ID): Image @proxy(get: "/$id.json")
    user(name: ID): User @proxy(get: "/profiles/$name.json")
    search(
        query: String!
        sort: SortFieldInput = created_at
        order: SortOrderInput = desc
    ): SearchPage! @proxy(get: "/search?q=$query&sf=$sort&sd=$sort_order")
}

scalar CommaSpaceSeparatedString
scalar Date
scalar Extension
scalar Mime
scalar Sha512
scalar Url

enum UserRole {
    user
}

enum InteractionType {
    voted
    faved
}

enum InteractionValue {
    up
    down
}

enum SortFieldInput {
    created_at
    updated_at
    first_seen_at
    score
    wilson
    relevance
    width
    height
    comments
    tag_count
    random
}

enum SortOrderInput {
    asc
    desc
}

type Image {
    aspect_ratio: Float!
    comment_count: Int!
    created_at: Date!
    description: String
    downvotes: Int!
    faves: Int!
    file_name: String
    first_seen_at: Date
    height: Int!
    id: ID!
    image: Url
    interactions: [Interaction!]!
    is_optimized: Boolean!
    is_rendered: Boolean!
    mime_type: Mime
    orig_sha512_has: Sha512
    original_format: Extension
    representations: Representations
    score: Int!
    sha512_hash: Sha512
    source_url: Url
    spoilered: Boolean
    tag_ids: [ID!]!
    tags: CommaSpaceSeparatedString
    updated_at: Date!
    uploader_id: Int
    uploader: String
    uploader_info: User @proxy(get: "/profiles/$uploader.json")
    upvotes: Int!
    width: Int!
}

type Interaction {
    id: ID
    image_id: ID
    image: Image @proxy(get: "/$image_id.json")
    interaction_type: InteractionType
    user_id: ID
    user: User @proxy(get: "/profiles/$user_id.json")
    value: InteractionValue
}

type Representations {
    thumb_tiny: Url
    thumb_small: Url
    thumb: Url
    small: Url
    medium: Url
    large: Url
    tall: Url
    full: Url
}

type SearchPage {
    search: [Image!]!
    total: Int!
    interactions: [Interaction!]!
}

type User {
    avatar_url: Url
    awards: [String!]!
    comment_count: Int!
    created_at: Date!
    description: String
    id: ID
    links: [String!]!
    name: String!
    post_count: Int!
    role: UserRole!
    slug: String!
    topic_count: Int!
    uploads_count: Int!
}
